site_name: batchling
site_url: https://vienneraphael.github.io/batchling/
repo_name: vienneraphael/batchling
repo_url: https://github.com/vienneraphael/batchling
site_dir: docs-site
strict: true
exclude_docs: architecture/**

theme:
  name: material
  logo: assets/images/batchling.png
  favicon: assets/images/batchling.png
  pygments_style: tango
  pygments_style_dark: monokai
  font:
    text: IBM Plex Sans
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      accent: grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: grey
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - toc.follow

plugins:
  - search
  - mkdocstrings:
      default_handler: python

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.snippets:
      base_path:
        - .
        - docs
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - toc:
      permalink: true

extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/bash-command-highlight.js
extra:
  generator: false

nav:
  - batchling:
      - batchling: index.md
      - Quickstart: quickstart.md
  - Documentation:
      - Core components:
          - Python SDK: python-sdk.md
          - CLI: cli.md
      - Frameworks & Providers:
          - Overview: overview.md
          - Frameworks: frameworks.md
          - Providers: providers.md
      - Use-Cases: use-cases.md
      - Advanced Features:
          - Advanced Features: advanced-features.md
          - Cache: cache.md
          - Dry Run: dry-run.md
          - Deferred Mode: deferred-mode.md
